name: Build Thrift
on:
  push:
    branches: [ "main" ]
jobs:
  post-0-9-3:
    strategy:
      fail-fast: false
      matrix:
        arch: [ armv7, aarch64, s390x, ppc64le, amd64 ]
        version: [ 0.9.3, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.18.1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir artifacts
      - name: Build Thrift ${{ matrix.version }} on ${{ matrix.arch }}
        uses: amousavigourabi/run-on-arch-action@v0
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu16.04
          dockerRunArgs: |
            --volume "$(pwd)/artifacts:/artifacts"
            --volume "$(pwd)/linux:/linux"
          shell: /bin/sh
          run: |
            apt-get -y update
            apt-get -y install wget tar make
            apt-get -y install g++ libboost-all-dev
            apt-get -y install autoconf automake
            ./linux/compile-post-0-9-3.sh ${{ matrix.version }}
            mv /usr/local/bin/thrift /artifacts/thrift
      - name: Retrieve binary from mount
        run: |
          mkdir -p ${{ matrix.version }}
          mv $(pwd)/artifacts/thrift ${{ matrix.version }}/thrift-linux_${{ matrix.arch }}.exe
      - name: Upload binary
        uses: amousavigourabi/push-action@v0
        with:
          message: |
            Upload Thrift binaries
            Upload the Thrift ${{ matrix.version }} binary for ${{ matrix.arch }} machines.
          files: ${{ matrix.version }}/thrift-linux_${{ matrix.arch }}.exe
          branch: release-dev
          rebase: true
  pre-0-9-2:
    strategy:
      fail-fast: false
      matrix:
        arch: [ armv7, aarch64, s390x, ppc64le, amd64 ]
        version: [ 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          ls
          mkdir artifacts
      - name: Build Thrift ${{ matrix.version }} on ${{ matrix.arch }}
        uses: amousavigourabi/run-on-arch-action@v0
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu16.04
          dockerRunArgs: |
            --volume "$(pwd)/artifacts:/artifacts"
            --volume "$(pwd)/linux:/linux"
          shell: /bin/sh
          run: |
            apt-get -y update
            apt-get -y install wget tar make
            apt-get -y install g++ libboost-all-dev
            apt-get -y install autoconf automake
            ./linux/compile-pre-0-9-2.sh ${{ matrix.version }}
            mv /usr/local/bin/thrift /artifacts/thrift
      - name: Retrieve binary from mount
        run: |
          ls
          mkdir -p ${{ matrix.version }}
          mv $(pwd)/artifacts/thrift ${{ matrix.version }}/thrift-linux_${{ matrix.arch }}.exe
      - name: Upload binary
        uses: amousavigourabi/push-action@v0
        with:
          message: |
            Upload Thrift binaries
            Upload the Thrift ${{ matrix.version }} binary for ${{ matrix.arch }} machines.
          files: '${{ matrix.version }}/thrift-linux_${{ matrix.arch }}.exe .gitattributes'
          branch: 'release-dev'
          rebase: true
