name: Stage binaries
on:
  workflow_run:
    workflows: [ "Build Thrift" ]
    types:
      - completed
jobs:
  commit-binaries:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout --orphan release
      - name: Download binaries
        uses: actions/download-artifact@v3
      - name: Push binaries
        run: |
          git commit -am "Upload Thrift binaries"
          git push origin HEAD
